name: fundus
description: Local-first media library and playback client.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.11.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  fundus_core: any
  fundus_design: any
  fundus_server: any
  path: ^1.9.1
  path_provider: ^2.1.6
  file_picker: ^11.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
